name = "cloudflare-agent-zyt"
main = "src/index.ts"
compatibility_date = "2026-02-22"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "ChatAgent"
class_name = "ChatAgent"

[[migrations]]
tag = "v1"
new_classes = ["ChatAgent"]

# 本地开发 Durable Object 存储
[[durable_objects.storage]]
binding = "ChatAgent"
id = "local"